spring:
  datasource:
    username: user
    password: pass
    url: jdbc:h2:file:./db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
products:
  url:
    base: 'http://localhost:9090/api/v1/product'
    list: ${products.url.base}/list
    get: ${products.url.base}/get/{0}
    saveAll: ${products.url.base}/saveAll
    create: ${products.url.base}/create
    edit: ${products.url.base}/update
    delete: ${products.url.base}/delete/{0}
logging:
  level:
    org.zalando.logbook: info
logbook:
  predicate:
    exclude:
      - path: /api/posts/comments