spring:
  datasource:
    url: jdbc:h2:mem:~
    username: user
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 10m
